title:             Isaac Menchaca
email:             imenc001@ucr.edu
description:       Bioengineering graduate interested in data science, machine learning, biosignals, and computational neuroscience.

author:            Isaac Menchaca
baseurl:           "" # Leave this alone if this is your main site (i.e. username.github.io). If instead this is a site for a project, e.g. username.github.io/
url:               "https://isaacmenchaca.github.io" # or http://username.github.io/mycleverproject if it is a project site, or http://mylovelydomainname.com if you have a domain, and so on.

collections:
  pages:
    output: true
    permalink: /:name

# Social Profiles
twitter_username: imenc001
github_username:   isaacmenchaca
facebook_username:
instagram_username:
linkedin_username: imenc001

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
